databases:
  - name: postgres
    ipAllowList: []
    databaseName: ruby_rails_boilerplate
    user: ruby_rails_boilerplate

services:
  - type: web
    name: ruby_rails_boilerplate
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
